fixed crash in compiled jar & better syntax
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "root" is null
	at de.idiotischer.bob.util.MainConfigUtil.reload(MainConfigUtil.java:23)
	at de.idiotischer.bob.util.MainConfigUtil.<init>(MainConfigUtil.java:16)
	at de.idiotischer.bob.BOB.init(BOB.java:65)
	at de.idiotischer.bob.BOB.<init>(BOB.java:61)
	at de.idiotischer.bob.BOB.main(BOB.java:51)
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:557)
	at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:468)
	at de.idiotischer.bob.scenario.ScenarioManager.getRandom(ScenarioManager.java:57)
	at de.idiotischer.bob.BOB.init(BOB.java:72)
	at de.idiotischer.bob.BOB.<init>(BOB.java:61)
	at de.idiotischer.bob.BOB.main(BOB.java:51)